# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}
# Orchestrate or schedule a set of jobs
jobs:
  my_err_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: return 1
      - run:
          name: on error
          command: echo "Hello Error!"
          when: on_fail
  print_wfid:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id
  print_hello:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - run: echo "hello" 
  print_world:
     docker: 
      - image: circleci/node:13.8.0
     steps:
      - run: echo "world "
      - run: echo $devname
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - print_hello
      - print_world: 
          requires:
            - print_hello
      - print_wfid
      - my_err_job
